# Generated by Django 4.2.5 on 2024-03-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tpoapi.job'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
