# Generated by Django 4.2.5 on 2024-03-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0002_application_job_studentprofile_is_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='tpo',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tpoapi.application'),
        ),
    ]
