# Generated by Django 4.2.11 on 2024-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0003_remove_interviewschedule_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
    ]
