# Generated by Django 4.2.11 on 2024-04-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0004_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
    ]
