# Generated by Django 4.2.5 on 2024-04-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0005_alter_interviewschedule_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
